### ISSUE TITLE
Enhanced Cross-Tenant Spoofing Protections

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#184]

**Comment by wez** [comment]
How about something like this for the queue helper?

```toml
[tenant.'mytenant']
require_authz = ["mytenant"]
allowed_domains = ["mytenant.com"]
```

When `queue_helper:apply(msg)` is called, if `allowed_domains` is set for the tenant that is determined for the current message, then the `MAIL FROM` and `From:` must both match values from that list, otherwise the message will be rejected.

If you have:

```toml
default_tenant = "default-tenant"

[tenant."default-tenant"]
allowed_domains = []
```

that will effectively prevent unknown/unspecified tenants from sending mail.

For this to work effectively, every valid tenant must have `require_authz` and `allowed_domains` configured.
