### ISSUE TITLE
SuspendTenant not working in global or sitename scope

### ISSUE THREAD

**Issue by MHillyer** [KumoCorp/kumomta#290]
### What Operating System are you seeing this problem on?

Ubuntu

### What Hardware is this system running?

VM

### KumoMTA version

Latest Dev

### Did you try the latest release to see if the issue is better (or worse!) than your current version?

Yes, and I updated the version box above to show the version that I tried

### Describe the bug

As reported by a customer:

We have clear evidence that SuspendTenant doesn't work in the global default scope or in a sitename scope. Even though this tenant gets suspended, it still seems to be attempting deliveries every 1s or so.

```toml   
    [["default".automation]]
    regex = "unusual rate of mail originating from your DKIM domain"
    trigger = "Immediate"
    action = "SuspendTenant"
    duration = "15 minutes"
```

This graph is showing [gmail.com](http://gmail.com/) only errors for things like Gmail has detected an unusual rate of mail originating from your DKIM domain that match the above TSA and create the 5m (known bug) suspensions. Graph is showing one specific account, with only those deferral error types, and one egress IP. The pattern is consistent across other IPs that this sender is sending from.

![image](https://github.com/user-attachments/assets/7ec3f7a0-4a8b-45bc-a83f-0e639c71217b)

### To Reproduce

Configure a SuspendTenant automation in a Global or Sitename Scope

### Configuration

See above

### Expected Behavior

Should suspend, does not properly suspend.
