### ISSUE TITLE
For convenience, allow shaping automation to list multiple patterns and multiple config changes

### ISSUE THREAD

**Issue by wez** [KumoCorp/kumomta#99]
so instead of:

```toml
[["example.com".automation]]
regex = 'Our system has detected an unusual rate'
action = {SetConfig={name="max_message_rate", value="1/minute"}}
trigger = "Immediate"
duration = "2m"

[["example.com".automation]]
regex = 'Our system has detected an unusual rate'
action = {SetConfig={name="connection_limit", value=1}}
trigger = "Immediate"
duration = "2m"
```

you could write something like this, assuming that the toml parser is ok with it:

```toml
[["example.com".automation]]
regex = 'Our system has detected an unusual rate'
action = [
  {SetConfig={name="max_message_rate", value="1/minute"}},
  {SetConfig={name="connection_limit", value=1}}
]
trigger = "Immediate"
duration = "2m"
```

also, multiple regexes:

```toml
[["example.com".automation]]
regex = [
  'Our system has detected an unusual rate',
  'you are sending too fast'
]
action = [
  {SetConfig={name="max_message_rate", value="1/minute"}},
  {SetConfig={name="connection_limit", value=1}}
]
trigger = "Immediate"
duration = "2m"
```
